/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import com.formdev.flatlaf.themes.FlatMacDarkLaf;
import java.awt.CardLayout;
import utils.ImageHelper;

/**
 *
 * @author ducanh123
 */
public class MainFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainFrame.class.getName());

    /**
     * Creates new form BigFrame
     */
    public MainFrame(String role) {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        this.setIconImage(ImageHelper.getAppIcon());
        CardLayout layout = (CardLayout) parentFrame.getLayout();
        if (role.equals("admin")) {
            layout.show(parentFrame, "cardAdmin");
        }
        else {
            layout.show(parentFrame, "cardUser");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        parentFrame = new javax.swing.JPanel();
        panelAdmin1 = new view.PanelAdmin();
        panelUser2 = new view.PanelUser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lý thuê xe");

        parentFrame.setLayout(new java.awt.CardLayout());
        parentFrame.add(panelAdmin1, "cardAdmin");
        parentFrame.add(panelUser2, "cardUser");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(parentFrame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(parentFrame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        FlatMacDarkLaf.setup();
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainFrame("admin").setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private view.PanelAdmin panelAdmin1;
    private view.PanelUser panelUser2;
    private javax.swing.JPanel parentFrame;
    // End of variables declaration//GEN-END:variables
}
